### ISSUE TITLE
Could not find gem 'jekyll-rdf (>= 0) ruby'  in source …

### ISSUE THREAD

**Issue by white-gecko** [DTP16/jekyll-rdf#16]
I get the following error, when I try to run jekyll with jekyll-rdf on my system:

```
/usr/lib/ruby/vendor_ruby/bundler/resolver.rb:357:in `resolve': Could not find gem 'jekyll-rdf (>= 0) ruby' in source at ../. (Bundler::GemNotFound)
Source does not contain any versions of 'jekyll-rdf (>= 0) ruby'
	from /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:164:in `start'
	from /usr/lib/ruby/vendor_ruby/bundler/resolver.rb:129:in `resolve'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:193:in `resolve'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:132:in `specs'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:177:in `specs_for'
	from /usr/lib/ruby/vendor_ruby/bundler/definition.rb:166:in `requested_specs'
	from /usr/lib/ruby/vendor_ruby/bundler/environment.rb:18:in `requested_specs'
	from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:13:in `setup'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:121:in `setup'
	from <my home>/.gem/gems/jekyll-3.1.3/lib/jekyll/plugin_manager.rb:33:in `require_from_bundler'
	from <my home>/.gem/gems/jekyll-3.1.3/bin/jekyll:9:in `<top (required)>'
	from ../../install/bin/jekyll:23:in `load'
	from ../../install/bin/jekyll:23:in `<main>'

```

This might be due to the fact, that I've installed the gems to an `install/` directory next to the source and have a local `.gem` directory in my home. But `Could not find gem 'jekyll-rdf (>= 0) ruby'  in source …` still looks strange (`'jekyll-rdf (>= 0) ruby'` instead of something like 'jekyll-rdf (>= 0)')

Maybe you can help me with this problem.

**Comment by lordon** [comment]
Does `jekyll-rdf (0.0.0)` appear when you run `gem list | grep 
jekyll-rdf`? If not, you should reinstall `jekyll-rdf` into your local 
gem directory.

**Comment by white-gecko** [comment]
yes.

    $ gem list | grep jekyll-rdf
    jekyll-rdf (0.0.0)

I think there must be a typo somewhere, since it says `'jekyll-rdf (>= 0) ruby'` in the error message.

**Comment by lordon** [comment]
Uhm. Can you please post your jekyll `_config.yml` here? Thx.

**Comment by white-gecko** [comment]
It this one https://github.com/DTP16/jekyll-rdf/blob/d30cacb093015ec8522cbd830287382b7ad18daa/test/source/_config.yml I try to build your example.

**Comment by lordon** [comment]
Try to change line 23 to `gems: [jekyll-rdf]` and make sure you have 
*no* `Gemfile` in the site's directory with something like this `gem 
'jekyll-rdf', :path => '../'` this is just for running in our test env

**Comment by white-gecko** [comment]
Cool, just removing the `Gemfile` broad me quite a bit further, but still an error:

```
Configuration file: <my path>/_config.yml
            Source: <my path>/source
       Destination: <my path>/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.1.3 | Error:  key not found: "jekyll_rdf"
```

**Comment by lordon** [comment]
Do you have something similar to this in your config?
```
jekyll_rdf:
     path: "simpsons.ttl"
```

**Comment by white-gecko** [comment]
Ok, sorry the path to the model was missing:

```
…
gems: [jekyll-rdf]

jekyll_rdf:
    path: "rdf-data/simpsons.ttl"
```
