### ISSUE TITLE
Serving resources ending with slash not possible

### ISSUE THREAD

**Issue by white-gecko** [DTP16/jekyll-rdf#17]
It is not possible to serve resources which are ending on a slash. E.g.

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .

<http://example.org/> rdf:type foaf:Person .
<http://example.org/> foaf:name "Example" .
```

A file `.html` will be generated. Which can't be served, at least with jekyll serve.

**Comment by lordon** [comment]
We should switch to this concept: https://jekyllrb.com/docs/pages/#named-folders-containing-index-html-files
Do you agree?

**Comment by white-gecko** [comment]
Yes, that sounds good.

(just for later reference:)
For distinguishing between the actual resource, the HTML resource and potentially an RDF resource (cf. https://www.w3.org/TR/cooluris/#semweb) still some kind of proxy with redirects and content negotiation can be used in front of the static pages.

**Comment by white-gecko** [comment]
Moved to https://github.com/white-gecko/jekyll-rdf/issues/24
